{% set name = "alvisnlp" %}
{% set version = "1.0.0" %}

about:
    home: https://github.com/Bibliome/alvisnlp
    license: Apache Licence 2.0
    summary: ALvisNLP/ML corpus processing engine

package:
    name: alvisnlp
    version: {{ version }}

build:
  number: 0

source:
  git_rev: 0.5	
  git_url: https://github.com/Bibliome/alvisnlp.git
  md5: 5f418d257fa20ac3219e70bf7dd32b5f

requirements:
  build:
    - maven
  run:
    - openjdk >=8

test:
    commands:
      - alvisnlp -help

extra:
  notes: |
    Alvisnlp is workflow engine composed of Java programs that are an enactor and a list of components.
